name: Generate PCB Fabrication Files
on: [push]

permissions:
  contents: write

jobs:
  kicad-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run KiCad DRC and Export
        run: |
          docker run --rm --user root -v ${{ github.workspace }}:/workspace -w /workspace kicad/kicad:8.0 sh -c "
            kicad-cli pcb drc --severity-error pcb_inlet.kicad_pcb -o drc_report.txt || true
            mkdir -p gerber_output
            kicad-cli pcb export gerbers pcb_inlet.kicad_pcb -o gerber_output/
            kicad-cli pcb export drill pcb_inlet.kicad_pcb -o gerber_output/
          "

      - name: Commit and Push Gerbers to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gerber_output/ drc_report.txt
          git commit -m "Automatyczny zapis Gerberów [skip ci]" || echo "Brak zmian do zapisu"
          git push
